openapi: 3.0.4
info:
  title: CatholicData - OpenAPI 3.0
  description: |-
    This document is an OpenAPI 3.0 specification describing the data model for catholicdata.org.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://catholicdata.org/
paths:
  /data/regions.json:
    get:
      summary: Geographic areas.
      description: Regions include both secular (governmental, regional) boundaries as well as ecclesiastical ones (defined by the Church).
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Region'
  /data/places.json:
    get:
      summary: Geographic points.
      description: Places are points of interest such as basilicas and churches.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
  /data/people.json:
    get:
      summary: People.
      description: "Notable Catholics and people connected to the Catholic church: saints, popes, cardinals, bishops, and more."
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
  /data/organizations.json:
    get:
      summary: Organizations.
      description: Notable Catholic organizations such as orders, charitable and service organizations, and more.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Organization"
  /data/documents.json:
    get:
      summary: Documents.
      description: Important Catholic documents such as papal encyclicals and bulls, church council documents, and books and other writings of notable saints.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Document"
components:
  schemas:
    Region:
      type: object
      properties:
        id:
          type: string
          example: region/ecclesiastical/roman/usa/wi/madison
        name:
          type: string
          example: Diocese of Madison
        domain:
          type: string
          enum:
            - Secular
            - Ecclesiastical
            - Other
          example: Ecclesiastical
        type:
          type: string
          enum:
            - Country
            - State
            - Province
            - County
            - Archdiocese
            - Archeparchy
            - Eparchy
            - Diocese
            - Apostolic Prefecture
            - Military Ordinariate
            - Personal Ordinariate
            - Territorial Prelature
            - Apostolic Administration
            - Personal Prelature
            - Secretariat
            - Other
          example: Diocese
        historical:
          type: boolean
          description: Whether the region is no longer recognized or active today.
          example: false
        location:
          allOf:
            - $ref: '#/components/schemas/Location'
            - type: object
              properties:
                timezone:
                  type: string
                  description: The primary timezone of this region.
                  example: -6
                geojson:
                  description: The URL to a GeoJSON file containing the boundary data for this region
                  type: string
                  format: url
                  example: https://catholicdata.org/geojson/ecclesiastical/wisconsin-madison.geojson
        contact:
          $ref: '#/components/schemas/Contact'
        socials:
          $ref: '#/components/schemas/Socials'
        parentIDs:
          description: A list of IDs of parent Regions this region is contained within. (A Region can have multiple parent Regions, for example a Dicoese may have both the State it is located in and the Archdiocese whose jurisdiction it falls within.)
          type: array
          items:
            description: The ID of another Region.
            type: string
            example: region/ecclesiastical/roman/usa/wi/milwaukee
        childIDs:
          description: A list of IDs of child Regions this region contains.
          example: []
          type: array
          items:
            description: The ID of another Region.
            type: string
        createdTime:
          description: The date and time this Region entered the dataset.
          type: string
          format: date-time
          example: 2020-08-20 18:44:37
        modifiedTime:
          description: The date and time this Region was last modified
          type: string
          format: date-time
          example: 2020-08-20 20:36:32
        sources:
          $ref: '#/components/schemas/Sources'
    Place:
      type: object
      properties:
        id:
          type: string
          example: place/cathedral/usa-wi-madison/st-raphael
        name:
          type: string
          example: Cathedral of St. Raphael
        historical:
          type: boolean
          description: Whether the place no longer exists or is recognized today.
          example: true
        type:
          type: string
          enum:
            - National Shrine
            - Major Basilica
            - Minor Basililca
            - Basilica
            - Cathedral
            - Church
            - School
            - Shrine
            - Mission
            - Abbey
            - Monastery
            - Convent
            - Other
          example: Cathedral
        location:
          allOf:
            - $ref: '#/components/schemas/Location'
            - type: object
              properties:
                googlePlaceID:
                  type: string
                  description: The Google Place ID for this place (see https://developers.google.com/maps/documentation/places/web-service/place-id).
                  example: EicxMyBNYXJrZXQgU3QsIFdpbG1pbmd0b24sIE5DIDI4NDAxLCBVU0E
        socials:
          $ref: '#/components/schemas/Socials'
        contact:
          $ref: '#/components/schemas/Contact'
        parentRegions:
          description: A list of IDs of parent Regions this place is located within.
          type: array
          items:
            description: The ID of a Region.
            type: string
            example: region/ecclesiastical/roman/usa/wi/madison
        sources:
          $ref: '#/components/schemas/Sources'
        
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
    Organization:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Document:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
    Event:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    
    Socials:
      description: Social media information associated with an object.
      type: object
      properties:
        facebook:
          description: The URL of the Facebook page or account for this region.
          type: string
          format: url
          example: https://www.facebook.com/madisondiocese
        twitter:
          description: The URL of the Twitter or X account for this region.
          type: string
          format: url
          example: https://twitter.com/MadisonDiocese
        instagram:
          description: The URL of the Instagram account for this region.
          type: string
          format: url
        youtube:
          description: The URL of the YouTube account for this region.
          type: string
          format: url
          example: https://www.youtube.com/channel/UCe5Nhw392UTDm7pMpTMEy6Q
    Location:
      description: The location of a Place or Region.
      type: object
      properties:
        address:
          description: The physical address.
          type: string
          example: >
            222 West Main Street
            Madison, WI 53703
        country:
          description: The name of the country this Place or Region is located within.
          type: string
          example: United States
        state:
          description: The name of the state or province this Place or Region is located within.
          type: string
          example: Wisconsin
        city:
          description: The name of the town or city this Place or Region is located within.
          type: string
          example: Madison
        latitute:
          type: number
          format: double
          description: The latitude of a Place, or of the principal point in or centroid of a Region.
          example: 43.073052
        longitude:
          type: number
          format: double
          description: The longitude of a Place, or of the principal point in or centroid of a Region
          example: -89.40123
    Contact:
      description: Contact information associated with a Region, Place, or Person.
      type: object
      properties:
        address:
          description: A mailing address for contacting this Region.
          type: string
          example: |
            702 South High Point Road, Suite 225
            Madison, WI 53719
        email:
          description: An email address for contacting this Region.
          type: string
          example: communication@madisondiocese.org
        phone:
          description: A phone number for contacting this Region.
          type: string
          example: +1-608-821-3000
        fax:
          description: A fax number for contacting this Region.
          type: string
          example: +1-608-440-2808
        website:
          description: The primary website for this Region.
          type: string
          format: url
          example: https://www.madisondiocese.org/
    Sources:
      description: A list of URLs that serve as sources for this data item.
      type: array
      items:
        description: The URL of a source.
        type: string
        format: url
      example:
        - https://en.wikipedia.org/wiki/Roman_Catholic_Diocese_of_Madison
        - https://www.catholic-hierarchy.org/diocese/dmadi.html